# app/indices.py

INDICES = {
    "NIFTY 50": "NSE:NIFTY50-INDEX",
    "NIFTY BANK": "NSE:NIFTYBANK-INDEX",
    "NIFTY IT": "NSE:CNXIT-INDEX",
    "NIFTY FMCG": "NSE:CNXFMCG-INDEX",
    "NIFTY AUTO": "NSE:NIFTYAUTO-INDEX",
    "NIFTY METAL": "NSE:CNXMETAL-INDEX",
    "NIFTY PHARMA": "NSE:CNXPHARMA-INDEX",
    "NIFTY MEDIA": "NSE:CNXMEDIA-INDEX",
    "NIFTY ENERGY": "NSE:CNXENERGY-INDEX"
}
